language: node_js
node_js:
- 0.6

before_script:
- "curl -o resources/js-test-driver/JsTestDriver-1.3.3d.jar 'http://js-test-driver.googlecode.com/files/JsTestDriver-1.3.3d.jar'"
- "java -jar resources/js-test-driver/JsTestDriver-1.3.3d.jar --basePath resources/js-test-driver --config resources/js-test-driver/jsTestDriver.conf --port 9876 &"
- "sleep 3"
- "phantomjs resources/js-test-driver-phantomjs/phantomjs-jstd.js &"
- "sleep 3"
